greenhouse: WebServer Class Reference
WebServer Class Reference
#include <webserver.h>
Public Member Functions
WebServer (Database *database)
int start ()
void tick ()
TCPSocket * getSocket ()
Detailed Description
Definition at line 65 of file webserver.h.
Constructor & Destructor Documentation
WebServer()
WebServer::WebServer (Database * database)
Definition at line 25 of file webserver.cpp.
 { db = database; }
References db.
Member Function Documentation
getSocket()
TCPSocket * WebServer::getSocket ()
Get the underlying socket.
Use this socket to close the server.
Return values
Socket
Definition at line 161 of file webserver.cpp.
 { return client_socket; }
References client_socket.
start()
int WebServer::start ()
Starts the webserver
Return values
void
Definition at line 27 of file webserver.cpp.
                      {
   net = new EthernetInterface;
   if (!net) {
     return 0;
   }
   net->set_network(IP, NETMASK, GATEWAY); // include to use static IP address
   nsapi_size_or_error_t r = net->connect();
   if (r != 0) {
     printf("[webserver]: error! net->connect() returned: %d\n", r);
     return r;
   }
   // Show the network address
   SocketAddress ip;
   SocketAddress netmask;
   SocketAddress gateway;
   net->get_ip_address(&ip);
   net->get_netmask(&netmask);
   net->get_gateway(&gateway);
   ip.set_port(PORT);
   const char *ip_addr = ip.get_ip_address();
   const char *netmask_addr = netmask.get_ip_address();
   const char *gateway_addr = gateway.get_ip_address();
   printf("[webserver]: IP address: %s\n", ip_addr ? ip_addr : "None");
   printf("[webserver]: Netmask: %s\n", netmask_addr ? netmask_addr : "None");
   printf("[webserver]: Gateway: %s\n", gateway_addr ? gateway_addr : "None");
   server.open(net);
   server.bind(ip);
   server.listen(MAX_CONN);
   return 1;
 };
References GATEWAY, IP, MAX_CONN, net, NETMASK, PORT, and server.
Referenced by main().
tick()
void WebServer::tick ()
One "revolution" of parsing incoming/outgoing connections
Return values
void
Definition at line 91 of file webserver.cpp.
                      {
   printf("=========================================\n");
   nsapi_error_t error = 0;
   client_socket = server.accept(&error);
   requests++;
   if (error != 0) {
     printf("[webserver]: Connection failed!\n");
   } else {
     client_socket->set_timeout(
         0); // timeout of 0 makes it a non-blocking connection
     client_socket->getpeername(&client_address);
     printf("[webserver]: Client with IP address %s connected.\n",
            client_address.get_ip_address());
     error = client_socket->recv(rx_buffer, sizeof(rx_buffer));
     switch (error) {
     case 0:
       printf("[webserver]: Recieved buffer is empty.\n");
       http_internal_server_error();
       break;
     case -1:
       printf("[webserver]: Failed to read data from client.\n");
       http_internal_server_error();
       break;
     default:
       printf("[webserver]: Recieved Data: %d bytes\n%.*s\n", strlen(rx_buffer),
              strlen(rx_buffer), rx_buffer);
       printf("%c", rx_buffer[4]);
       if (rx_buffer[0] == 'G' && rx_buffer[1] == 'E' && rx_buffer[2] == 'T' &&
           rx_buffer[4] == '/' && rx_buffer[5] == ' ') {
         // setup http response header & data
         http_ok();
         strcpy(tx_buffer, homepage);
       } else if (rx_buffer[0] == 'P' && rx_buffer[1] == 'O' &&
                  rx_buffer[2] == 'S' && rx_buffer[3] == 'T') {
         // POST request
         string s = string(rx_buffer);
         int len = s.length();
         string data = s.substr(len - 11, len);
         string temp = data.substr(0, 4);
         string dewity = data.substr(4, 4).substr(1, 2); // wat 🤡
         string humidity = data.substr(8, 9);
         Row r = Row();
         r.temperature = temp;
         r.dewity = dewity;
         r.humidity = humidity;
         db->append(r);
         http_no_content();
       } else {
         http_not_found();
       }
       client_socket->send(tx_buffer, strlen(tx_buffer));
       break;
     }
   }
   client_socket->close();
 }
References Database::append(), client_address, client_socket, db, Row::dewity, homepage, http_internal_server_error(), http_no_content(), http_not_found(), http_ok(), Row::humidity, requests, rx_buffer, server, Row::temperature, and tx_buffer.
Referenced by webserver_task().
The documentation for this class was generated from the following files:
include/webserver.h
source/webserver.cpp