greenhouse: Tasks::Jukebox Class Reference
Tasks::Jukebox Class Reference
#include <jukebox_task.h>
Public Member Functions
void start ()
Detailed Description
Definition at line 5 of file jukebox_task.h.
Member Function Documentation
start()
void Tasks::Jukebox::start ()
Definition at line 15 of file jukebox_task.cpp.
{
   button.rise(_button_handler);
 }
References _button_handler(), and button().
Referenced by jukebox_task().
The documentation for this class was generated from the following files:
include/tasks/jukebox_task.h
source/tasks/jukebox_task.cpp