greenhouse: Tasks::Stats Class Reference
Tasks::Stats Class Reference
#include <stats_task.h>
Public Member Functions
Stats ()
void setDisplay (UI::Display *display)
void start ()
void stop ()
Detailed Description
Definition at line 7 of file stats_task.h.
Constructor & Destructor Documentation
Stats()
Tasks::Stats::Stats ()
Member Function Documentation
setDisplay()
void Stats::setDisplay (UI::Display * display)
Definition at line 17 of file stats_task.cpp.
{
     _display = display;
 }
References _display, and display.
Referenced by stats_task().
start()
void Stats::start ()
Definition at line 27 of file stats_task.cpp.
                   {
   if (_thread) {
     // we're already running
     return;
   }
   _thread_id = stats_queue->call_every(SAMPLE_TIME_MS, collect_stats);
   _thread = new Thread(osPriorityNormal, MAX_THREAD_STACK);
 }
References _thread, _thread_id, collect_stats(), MAX_THREAD_STACK, SAMPLE_TIME_MS, and stats_queue.
Referenced by stats_task().
stop()
void Stats::stop ()
Definition at line 38 of file stats_task.cpp.
                  {
   if (_thread) {
     _thread->terminate();
   }
 }
References _thread.
The documentation for this class was generated from the following files:
include/tasks/stats_task.h
source/tasks/stats_task.cpp