greenhouse: source/tasks/jukebox_task.cpp File Reference
jukebox_task.cpp File Reference
#include "jukebox_task.h"
#include "jukebox.h"
Functions
InterruptIn button (D2)
void _button_handler ()
Function Documentation
_button_handler()
void _button_handler ()
Definition at line 6 of file jukebox_task.cpp.
{
   if (Jukebox::is_playing()) {
     Jukebox::stop();
     return;
   }
   Jukebox::play();
 }
References Jukebox::is_playing(), Jukebox::play(), and Jukebox::stop().
Referenced by Tasks::Jukebox::start().
button()
InterruptIn button (D2)
Referenced by Tasks::Jukebox::start().