greenhouse: source/main.cpp File Reference
main.cpp File Reference
#include "Callback.h"
#include "EventQueue.h"
#include "Semaphore.h"
#include "ThisThread.h"
#include "database.h"
#include "mbed.h"
#include "mbed_wait_api.h"
#include "ui/ui.h"
#include "webserver.h"
#include <cstdlib>
#include "jukebox.h"
Macros
#define MAX_THREAD_STACK 384
#define SAMPLE_TIME_MS 1000
Functions
EventQueue queue (32 *EVENTS_EVENT_SIZE)
Semaphore s_db (1)
InterruptIn button (D2)
void button_handler ()
void jukebox_task ()
void webserver_task (WebServer *webServer)
void print_cpu_stats ()
int main (void)
Variables
Thread thread_main
Thread thread_web_server
Thread thread_jukebox
UI::Display * display
Macro Definition Documentation
MAX_THREAD_STACK
#define MAX_THREAD_STACK 384
Definition at line 13 of file main.cpp.
SAMPLE_TIME_MS
#define SAMPLE_TIME_MS 1000
Definition at line 14 of file main.cpp.
Function Documentation
button()
InterruptIn button (D2)
Referenced by jukebox_task().
button_handler()
void button_handler ()
Definition at line 27 of file main.cpp.
                       {
   if (Jukebox::is_playing()) {
     Jukebox::stop();
     return;
   }
   Jukebox::play();
 }
References Jukebox::is_playing(), Jukebox::play(), and Jukebox::stop().
Referenced by jukebox_task().
jukebox_task()
void jukebox_task ()
Definition at line 36 of file main.cpp.
                     {
   button.rise(button_handler);
 }
References button(), and button_handler().
Referenced by main().
main()
int main (void)
Definition at line 54 of file main.cpp.
                {
   display->init();
   thread_jukebox.start(jukebox_task);
   int id;
   Thread *thread_stats;
   EventQueue *stats_queue = mbed_event_queue();
   id = stats_queue->call_every(SAMPLE_TIME_MS, print_cpu_stats);
   thread_stats = new Thread(osPriorityNormal, MAX_THREAD_STACK);
   Database db;
   WebServer webServer = WebServer(&db);
   display->log((uint8_t *)"[webserver]: starting");
   int status = webServer.start();
   if (status == 0) {
     display->log((uint8_t *)"[webserver]: error - No network interface found");
     exit(1);
   }
   display->log((uint8_t *)"[webserver]: IP: 192.168.1.100");
   display->log((uint8_t *)"[host]: spawning webserver_thread");
   thread_web_server.start(callback(webserver_task, &webServer));
 }
References db, display, UI::Display::init(), jukebox_task(), UI::Display::log(), MAX_THREAD_STACK, print_cpu_stats(), SAMPLE_TIME_MS, WebServer::start(), thread_jukebox, thread_web_server, and webserver_task().
print_cpu_stats()
void print_cpu_stats ()
Definition at line 46 of file main.cpp.
 {
     mbed_stats_cpu_t stats;
     mbed_stats_cpu_get(&stats);
     display->update_stats(&stats, SAMPLE_TIME_MS);
 }
References display, SAMPLE_TIME_MS, and UI::Display::update_stats().
Referenced by main().
queue()
EventQueue queue (32 * EVENTS_EVENT_SIZE)
s_db()
Semaphore s_db (1)
webserver_task()
void webserver_task (WebServer * webServer)
Definition at line 40 of file main.cpp.
{
   while (true) {
     webServer->tick();
   }
 }
References WebServer::tick().
Referenced by main().
Variable Documentation
display
UI::Display* display
Definition at line 20 of file main.cpp.
Referenced by main(), and print_cpu_stats().
thread_jukebox
Thread thread_jukebox
Definition at line 18 of file main.cpp.
Referenced by main().
thread_main
Thread thread_main
Definition at line 16 of file main.cpp.
thread_web_server
Thread thread_web_server
Definition at line 17 of file main.cpp.
Referenced by main().