greenhouse: Jukebox Namespace Reference
Jukebox Namespace Reference
Functions
void play ()
void stop ()
bool is_playing ()
Function Documentation
is_playing()
bool Jukebox::is_playing ()
Definition at line 137 of file jukebox.cpp.
{
   return isPlaying;
 }
References isPlaying.
Referenced by button_handler().
play()
void Jukebox::play ()
Definition at line 97 of file jukebox.cpp.
                    {
   if (isPlaying) {
     return;
   }
   isPlaying = true;
   buzzer.resume();
   const int songspeed = 1.5;
   float result;
   float bzz = 0.5;
   for (int i = 0; i < 203; i++) {
     if (!isPlaying) {
       stop();
     }
     int w = duration[i] * songspeed;
     if (notes[i] == 0) {
       result = 1;
       bzz = 0;
     } else {
       result = 1 / notes[i];
       bzz = 0.4;
     }
     buzzer.period(result);
     buzzer.write(bzz);
     wait_us(w * 1000);
   }
   buzzer.suspend();
 }
References buzzer(), duration, isPlaying, notes, and stop().
Referenced by button_handler().
stop()
void Jukebox::stop ()
Definition at line 132 of file jukebox.cpp.
                    {
   buzzer.suspend();
   isPlaying = false;
 }
References buzzer(), and isPlaying.
Referenced by button_handler(), and play().