greenhouse: source/tasks/stats_task.cpp File Reference
stats_task.cpp File Reference
#include "Thread.h"
#include "mbed.h"
#include "tasks/stats_task.h"
#include "ui.h"
#include <cstdio>
Macros
#define SAMPLE_TIME_MS 1000
#define MAX_THREAD_STACK 384
Functions
void collect_stats ()
Variables
UI::Display * _display
EventQueue * stats_queue = mbed_event_queue()
int _thread_id
Thread * _thread
Macro Definition Documentation
MAX_THREAD_STACK
#define MAX_THREAD_STACK 384
Definition at line 10 of file stats_task.cpp.
SAMPLE_TIME_MS
#define SAMPLE_TIME_MS 1000
Definition at line 9 of file stats_task.cpp.
Function Documentation
collect_stats()
void collect_stats ()
Definition at line 21 of file stats_task.cpp.
                      {
   mbed_stats_cpu_t stats;
   mbed_stats_cpu_get(&stats);
   _display->update_stats(&stats, SAMPLE_TIME_MS);
 }
References _display, SAMPLE_TIME_MS, and UI::Display::update_stats().
Referenced by Tasks::Stats::start().
Variable Documentation
_display
UI::Display* _display
Definition at line 12 of file stats_task.cpp.
Referenced by collect_stats(), and Tasks::Stats::setDisplay().
_thread
Thread* _thread
Definition at line 15 of file stats_task.cpp.
Referenced by Tasks::Stats::start(), and Tasks::Stats::stop().
_thread_id
int _thread_id
Definition at line 14 of file stats_task.cpp.
Referenced by Tasks::Stats::start().
stats_queue
EventQueue* stats_queue = mbed_event_queue()
Definition at line 13 of file stats_task.cpp.
Referenced by Tasks::Stats::start().