greenhouse: source/ui/ui.cpp File Reference
ui.cpp File Reference
#include "ui/ui.h"
#include "Queue.h"
#include "mbed.h"
#include "stm32746g_discovery_lcd.h"
#include "stm32f7xx_hal.h"
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <queue>
#include <string>
#include <vector>
Functions
void set_default_font ()
string microsecond_to_sec_str (uint64_t us)
string make_stat_str (string label, string suffix, uint64_t us)
Variables
static const int MAX_LOG_LINES = 6
static const int LOG_Y_POS = 13
int log_idx = 0
uint64_t prev_idle_time = 0
Function Documentation
make_stat_str()
string make_stat_str (string label, string suffix, uint64_t us)
Definition at line 75 of file ui.cpp.
{
   string stat = string(label);
   stat.append(microsecond_to_sec_str(us));
   stat.append(suffix);
   return stat;
 }
References microsecond_to_sec_str().
Referenced by UI::Display::update_stats().
microsecond_to_sec_str()
string microsecond_to_sec_str (uint64_t us)
Definition at line 63 of file ui.cpp.
{
   uint64_t converted;
   if (us > 1) {
     converted = us / 1000 / 1000;
   } else {
     converted = 0;
   }
   return std::to_string(converted);
 }
Referenced by make_stat_str().
set_default_font()
void set_default_font ()
Definition at line 20 of file ui.cpp.
{
   BSP_LCD_SetFont(&Font12);
 }
Referenced by UI::Display::init().
Variable Documentation
log_idx
int log_idx = 0
Definition at line 17 of file ui.cpp.
Referenced by UI::Display::log().
LOG_Y_POS
const int LOG_Y_POS = 13 static
Definition at line 16 of file ui.cpp.
Referenced by UI::Display::init(), and UI::Display::log().
MAX_LOG_LINES
const int MAX_LOG_LINES = 6 static
Definition at line 15 of file ui.cpp.
Referenced by UI::Display::log().
prev_idle_time
uint64_t prev_idle_time = 0
Definition at line 18 of file ui.cpp.
Referenced by UI::Display::update_stats().